@base_url = http://127.0.0.1:5000
@id = 1

### Список
GET {{base_url}}/categories

### Создать
POST {{base_url}}/categories
Content-Type: application/json

{"name": "Обычные опросы"}

### Получить
GET {{base_url}}/categories/{{id}}

### Полностью обновить
PUT {{base_url}}/categories/{{id}}
Content-Type: application/json

{"name": "Необычные вопросы"}

### Частично обновить
PATCH {{base_url}}/categories/{{id}}
Content-Type: application/json

{"name": "Каверзные вопросы с двойным дном"}

### Удалить
DELETE {{base_url}}/categories/{{id}}
