@base_url = http://127.0.0.1:5000
@question_id = 1

### Список вопросов
GET {{base_url}}/questions
Accept: application/json

### Создать вопрос
POST {{base_url}}/questions
Accept: application/json
Content-Type: application/json

{
  "text": "Кто за четырехдневную рабочую неделю?"
}

### Получить вопрос
GET {{base_url}}/questions/{{question_id}}
Accept: application/json


### Получить второй вопрос
GET {{base_url}}/questions/2
Accept: application/json

### Обновить вопрос (PUT)
PUT {{base_url}}/questions/{{question_id}}
Accept: application/json
Content-Type: application/json

{
  "text": "Жизнь - тлен?"
}

### Обновить вопрос (PATCH)
PATCH {{base_url}}/questions/{{question_id}}
Accept: application/json
Content-Type: application/json

{
  "text": "Вам нравится работать?"
}

### Удалить вопрос
DELETE {{base_url}}/questions/{{question_id}}
Accept: application/json

### Создать вопрос в категории (категория 1 должна существовать)
POST {{base_url}}/questions
Content-Type: application/json

{"text": "Хочешь пива?", "category_id": 1}

### Снять категорию
PATCH {{base_url}}/questions/{{question_id}}
Content-Type: application/json

{"category_id": null}
